
const seed={plan:'core',credits:5,user:{name:'Alex',roles:['Full Stack Developer','Software Engineer'],location:'Remote / California',salary:'$95k+'},jobs:[
{id:1,title:'Full Stack Developer',company:'Northstar Labs',salary:'$110k–$135k',location:'Remote',match:94,why:'Strong React, Node and API alignment. Your current Full Stack résumé already fits this role.',resume:'Full Stack v2',status:'Suggested'},
{id:2,title:'Software Engineer II',company:'Orchard Systems',salary:'$102k–$128k',location:'Remote — US',match:91,why:'Excellent JavaScript/TypeScript overlap and solid product engineering fit.',resume:'Full Stack v2',status:'Saved'},
{id:3,title:'Frontend Engineer',company:'Motive House',salary:'$98k–$122k',location:'San Francisco / Remote',match:88,why:'Strong UI engineering match. One new résumé variant could foreground accessibility and design systems.',resume:'Frontend Focus',status:'Suggested'},
{id:4,title:'Platform Engineer',company:'Lumen Works',salary:'$118k–$145k',location:'Remote',match:82,why:'Good backend fit, with a modest gap around Kubernetes ownership.',resume:'Backend/API',status:'Suggested'},
{id:5,title:'Product Engineer',company:'Common Thread',salary:'$105k–$130k',location:'Remote',match:86,why:'Broad full-stack experience maps well to a small product team.',resume:'Full Stack v2',status:'Suggested'}],
applications:[{company:'Nimbus',role:'Full Stack Engineer',status:'Interview',date:'Oct 1'},{company:'Cedar AI',role:'Software Engineer',status:'Applied',date:'Sep 29'},{company:'Arcade Health',role:'Frontend Engineer',status:'Follow-up',date:'Sep 25'}],
resumes:[{name:'Master résumé',focus:'General full stack',updated:'Oct 1'},{name:'Full Stack v2',focus:'React + Node + APIs',updated:'Oct 4'},{name:'Backend/API',focus:'Node + systems',updated:'Sep 28'}],
experiences:[{title:'Handled launch-day scope change',text:'Rebuilt a release checklist and coordinated engineering, product, and support after requirements changed three days before launch.',star:'Adaptability · cross-functional coordination'}]};
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
let state=cloneSeed();
try{
  const stored=localStorage.getItem('laddrState');
  if(stored) state=JSON.parse(stored);
}catch(e){state=cloneSeed()}
function save(){try{localStorage.setItem('laddrState',JSON.stringify(state))}catch(e){}}
const $=s=>document.querySelector(s);const app=$('#app');
function brand(){return `<div class="brand"><span class="brandmark"></span><span class="serif">Ladd_r</span></div>`}
function top(){return `<header class="topbar">${brand()}<nav class="navlinks"><button class="desk" onclick="go('landing')">Home</button><button class="desk" onclick="go('pricing')">Pricing</button><button class="desk" onclick="go('dashboard')">Demo</button><button class="btn primary" onclick="go('dashboard')">Open Ladd_r</button></nav></header>`}
function mascot(){return `<div class="heroart"><div class="blob b1"></div><div class="blob b2"></div><div class="ladder">${'<i></i>'.repeat(8)}</div><div class="monster"><span class="smile"></span><span class="pack"></span></div></div>`}
function landing(){return `${top()}<main class="landing"><section class="hero"><div><div class="eyebrow">Discover what’s missing.</div><h1>Less searching.<br>More moving.</h1><p>Ladd_r is your job-search and career-growth assistant: focused opportunities, tailored materials, follow-up structure, interview prep, and a clear picture of what can move you higher.</p><div class="cta"><button class="btn primary" onclick="go('dashboard')">Explore the demo</button><button class="btn gold" onclick="go('pricing')">See plans</button></div><div class="trust">No placement promises. No hidden upgrade maze. Just useful work, clearly explained.</div></div>${mascot()}</section><section class="section"><h2>Everything that moves the search forward.</h2><p class="sub">The heart of Ladd_r is useful at every tier. Paid plans add automation and career depth—not access to a secretly functional version of the product.</p><div class="grid grid4" style="margin-top:24px"><div class="card teal"><div class="iconbubble">◎</div><h3>Readiness</h3><p>See what roles your experience already supports and where the real gaps are.</p></div><div class="card gold"><div class="iconbubble">⌕</div><h3>Search</h3><p>Receive a small set of strong opportunities instead of an endless job dump.</p></div><div class="card coral"><div class="iconbubble">↗</div><h3>Apply</h3><p>Reuse the right résumé, tailor only when it matters, and keep every application organized.</p></div><div class="card"><div class="iconbubble">☆</div><h3>Grow</h3><p>Capture work experiences, build interview stories, and discover higher-paying adjacent paths.</p></div></div></section>${pricingSection()}<section class="section"><div class="promise"><div><strong>What you see is what you get.</strong><div style="margin-top:8px;color:#ddd">Free is useful. Core is the complete job-search experience. Grow adds career development. Extra résumé credits only add volume.</div></div><button class="btn gold" onclick="go('dashboard')">Try the workspace</button></div></section></main><footer class="footer">Ladd_r · Discover what’s missing.</footer>`}
function pricingSection(){return `<section class="section" id="pricing"><h2>Simple plans. No surprise unlocks.</h2><p class="sub">Choose how much support you want. Optional extra résumé credits are available à la carte; they are never required to use the features included in your plan.</p><div class="grid grid3" style="margin-top:24px"><div class="card"><h3>Free</h3><div class="price">$0</div><ul class="cleanlist"><li>Résumé builder</li><li>Readiness snapshot</li><li>Basic tracker</li><li>Limited job suggestions</li></ul><button class="btn" onclick="setPlan('free')">Use Free</button></div><div class="card gold"><div class="eyebrow">Most popular</div><h3>Core</h3><div class="price">$7 <small>/ month</small></div><ul class="cleanlist"><li>5 focused matches each week</li><li>5 résumé credits / month</li><li>Cover-letter help</li><li>Application + follow-up support</li><li>Interview prep wizard</li></ul><button class="btn primary" onclick="setPlan('core')">Choose Core</button></div><div class="card teal"><h3>Grow</h3><div class="price">$12 <small>/ month</small></div><ul class="cleanlist"><li>Everything in Core</li><li>Experience Diary</li><li>STAR story bank</li><li>Salary-path analysis</li><li>Skill-gap recommendations</li></ul><button class="btn primary" onclick="setPlan('grow')">Choose Grow</button></div></div></section>`}
function pricing(){return `${top()}<main class="landing">${pricingSection()}<div class="promise"><div><strong>No extra upsells required.</strong><div style="margin-top:8px;color:#ddd">Need extra volume one month? Add résumé credits à la carte without changing plans.</div></div><button class="btn gold" onclick="addCredits(3)">Demo +3 credits</button></div></main>`}
const nav=[['dashboard','Home'],['matches','Matches'],['applications','Applications'],['resumes','Résumés'],['interview','Interview'],['grow','Grow'],['diary','Diary']];
function shell(page,body){return `${top()}<div class="shell"><aside class="sidebar"><div class="tier">${state.plan} plan · ${state.credits} résumé credits</div>${nav.map(([id,l])=>`<button class="sidebtn ${page===id?'active':''}" onclick="go('${id}')">${l}</button>`).join('')}<button class="sidebtn" onclick="go('pricing')">Plans</button></aside><main class="content">${body}</main><nav class="mobilebar">${nav.slice(0,5).map(([id,l])=>`<button onclick="go('${id}')">${l}</button>`).join('')}</nav></div>`}
function dashboard(){const applied=state.applications.length;return shell('dashboard',`<div class="pagehead"><div><div class="eyebrow">Your week</div><h1>Good afternoon, ${state.user.name}.</h1><div class="muted">A calmer search, one useful step at a time.</div></div><button class="btn gold" onclick="go('matches')">See this week’s 5</button></div><div class="stats"><div class="stat"><div class="muted">Fresh matches</div><b>5</b></div><div class="stat"><div class="muted">Applications</div><b>${applied}</b></div><div class="stat"><div class="muted">Follow-ups</div><b>${state.applications.filter(a=>a.status==='Follow-up').length}</b></div><div class="stat"><div class="muted">Resume credits</div><b>${state.credits}</b></div></div><div class="columns"><section class="card"><h3>Your strongest opportunities</h3>${state.jobs.slice(0,3).map(j=>jobRow(j)).join('')}<div style="margin-top:16px"><button class="btn" onclick="go('matches')">View all matches</button></div></section><aside class="card teal"><h3>Readiness</h3><div style="font-size:54px;font-weight:900;font-family:Georgia">88%</div><p>You’re highly aligned with full-stack and product-engineering roles in your current target band.</p><div class="progress"><i style="width:88%"></i></div><hr style="border:0;border-top:2px solid #151515;margin:20px 0"><b>Next level signal</b><p class="muted">Platform/cloud ownership appears often in higher-paying adjacent roles.</p>${state.plan==='grow'?'<button class="btn" onclick="go(\'grow\')">See growth path</button>':'<button class="btn" onclick="go(\'pricing\')">Preview Grow</button>'}</aside></div>`)}
function jobRow(j){return `<div class="mini job"><div><b>${j.title}</b> · ${j.company}<div class="jobmeta"><span class="tag">${j.salary}</span><span class="tag">${j.location}</span><span class="tag">${j.resume}</span></div></div><div><div class="match">${j.match}%</div><button class="btn" onclick="jobDetail(${j.id})">Review</button></div></div>`}
function matches(){return shell('matches',`<div class="pagehead"><div><div class="eyebrow">Weekly matches</div><h1>Five worth your time.</h1><div class="muted">If fewer than five meet your standards, Ladd_r should show fewer—not filler.</div></div><div class="pill">${state.credits} résumé credits</div></div><div class="card">${state.jobs.map(j=>jobRow(j)).join('')}</div>`)}
function jobDetail(id){const j=state.jobs.find(x=>x.id===id);const reuse=state.resumes.some(r=>r.name===j.resume);app.innerHTML=shell('matches',`<div class="pagehead"><div><button class="btn" onclick="go('matches')">← Back</button><h1 style="margin-top:16px">${j.title}</h1><div class="muted">${j.company} · ${j.location} · ${j.salary}</div></div><div class="match">${j.match}% match</div></div><div class="columns"><section class="card"><h3>Why Ladd_r picked it</h3><p>${j.why}</p><h3>Recommended résumé</h3><div class="mini"><b>${j.resume}</b><p class="muted">${reuse?'You already have a résumé strong enough for this posting. Save the credit.':'This role is distinct enough that a new variant may be worth one credit.'}</p></div><div class="cta" style="margin-top:16px"><button class="btn primary" onclick="applyJob(${j.id})">Mark applied</button><button class="btn ${reuse?'':'gold'}" onclick="tailor(${j.id})">${reuse?'Use existing résumé':'Tailor résumé · 1 credit'}</button></div></section><aside class="card gold"><h3>Interview angle</h3><p>Prepare one story about shipping under changing requirements and one story about technical tradeoffs across frontend and backend.</p><button class="btn" onclick="go('interview')">Open interview prep</button></aside></div>`)}
function applyJob(id){const j=state.jobs.find(x=>x.id===id);if(!state.applications.some(a=>a.company===j.company)){state.applications.unshift({company:j.company,role:j.title,status:'Applied',date:'Today'});save()}toast('Application added to your tracker.');go('applications')}
function tailor(id){const j=state.jobs.find(x=>x.id===id);if(state.resumes.some(r=>r.name===j.resume)){toast('Existing résumé selected. No credit used.');return}if(state.credits<1){toast('No résumé credits remaining.');return}state.credits--;state.resumes.unshift({name:j.resume,focus:j.title,updated:'Today'});save();toast('Tailored résumé created in demo mode. 1 credit used.');go('resumes')}
function applications(){return shell('applications',`<div class="pagehead"><div><div class="eyebrow">Application tracker</div><h1>Keep the thread.</h1><div class="muted">Every application, its status, and what should happen next.</div></div></div><div class="card"><table class="table"><thead><tr><th>Role</th><th>Company</th><th>Status</th><th>Added</th></tr></thead><tbody>${state.applications.map((a,i)=>`<tr><td>${a.role}</td><td>${a.company}</td><td><select class="select" onchange="updateApp(${i},this.value)">${['Saved','Applied','Follow-up','Interview','Offer','Rejected'].map(s=>`<option ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${a.date}</td></tr>`).join('')}</tbody></table></div>`)}
function updateApp(i,v){state.applications[i].status=v;save();toast('Status updated.')}
function resumes(){return shell('resumes',`<div class="pagehead"><div><div class="eyebrow">Résumé bank</div><h1>Reuse what already works.</h1><div class="muted">Tailoring is valuable when the job actually demands a different story.</div></div><div class="pill">${state.credits} credits</div></div><div class="grid grid3">${state.resumes.map(r=>`<div class="card"><h3>${r.name}</h3><p>${r.focus}</p><div class="muted">Updated ${r.updated}</div><div class="cta" style="margin-top:14px"><button class="btn" onclick="toast('Preview opened in demo mode.')">Preview</button><button class="btn" onclick="toast('Export prepared in demo mode.')">Export</button></div></div>`).join('')}<div class="card gold"><h3>Need another?</h3><p>Only create a new version when it materially changes how your experience maps to a role.</p><button class="btn" onclick="addCredits(1)">Demo +1 credit</button></div></div>`)}
function interview(){return shell('interview',`<div class="pagehead"><div><div class="eyebrow">Interview prep wizard</div><h1>Know your stories.</h1><div class="muted">Role-specific prompts, grounded in experiences you’ve actually had.</div></div></div><div class="columns"><section class="card"><h3>Practice prompt</h3><div class="mini"><b>Tell me about a time requirements changed late in a project.</b><p class="muted">Focus on the decision you made, who you coordinated with, and the measurable result.</p></div><div class="field" style="margin-top:16px"><label>Your answer</label><textarea id="answer" placeholder="Type a rough answer — polished is not required."></textarea></div><button class="btn primary" onclick="feedback()">Get feedback</button><div id="feedback"></div></section><aside class="card teal"><h3>Story bank</h3>${state.experiences.map(e=>`<div class="mini"><b>${e.title}</b><div class="muted">${e.star}</div></div>`).join('')}</aside></div>`)}
function feedback(){const v=$('#answer').value.trim();$('#feedback').innerHTML=`<div class="mini" style="margin-top:16px;background:#ffe38c"><b>${v?'Good raw material.':'Start with a real example.'}</b><p>${v?'Tighten the situation to one sentence, make your action unmistakably yours, and add a concrete result if you have one. Avoid inventing a metric just to make the answer sound stronger.':'Choose one real experience, even if it feels ordinary. Specific beats impressive.'}</p></div>`}
function grow(){if(state.plan!=='grow')return shell('grow',`<div class="card gold"><h1>Grow is the career layer.</h1><p>Core already includes the complete job-search experience. Grow adds salary-path analysis, experience capture, and next-level planning.</p><button class="btn primary" onclick="setPlan('grow')">Switch demo to Grow · $12</button></div>`);return shell('grow',`<div class="pagehead"><div><div class="eyebrow">Next level</div><h1>See what changes the range.</h1><div class="muted">Market signals, not salary guarantees.</div></div></div><div class="columns"><section class="card"><h3>Your current band</h3><div class="price">$98k–$135k</div><p>Strongest alignment: Full Stack Developer, Software Engineer II, Product Engineer.</p><h3 style="margin-top:28px">Higher-paying adjacent band</h3><div class="price">$118k–$155k</div><p>Common differentiators in otherwise similar postings:</p><ul class="cleanlist"><li>Cloud/platform ownership</li><li>Kubernetes or infrastructure depth</li><li>Technical mentorship</li></ul></section><aside class="card teal"><h3>Shortest practical paths</h3><div class="mini"><b>Demonstrate it</b><p>Build a deployable portfolio project showing CI/CD and cloud ownership.</p></div><div class="mini"><b>Gain it at work</b><p>Volunteer for deployment, observability, or platform responsibilities for 6–12 months.</p></div><div class="mini"><b>Learn it cheaply</b><p>Use a reputable low-cost cloud or Kubernetes course before considering an expensive bootcamp.</p></div></aside></div>`)}
function diary(){if(state.plan!=='grow')return shell('diary',`<div class="card teal"><h1>Experience Diary lives in Grow.</h1><p>Your job-search tools remain complete in Core. Diary is for turning what happens after you’re hired into future interview and promotion evidence.</p><button class="btn primary" onclick="setPlan('grow')">Switch demo to Grow</button></div>`);return shell('diary',`<div class="pagehead"><div><div class="eyebrow">Experience Diary</div><h1>Don’t forget what you did.</h1><div class="muted">Today’s messy work can become tomorrow’s interview story.</div></div></div><div class="columns"><section class="card"><div class="field"><label>What happened?</label><input id="expTitle" placeholder="Short title"><textarea id="expText" placeholder="Write it the way you remember it. Ladd_r can structure it later."></textarea></div><button class="btn primary" onclick="addExperience()">Save experience</button><h3 style="margin-top:28px">Saved experiences</h3>${state.experiences.map(e=>`<div class="mini"><b>${e.title}</b><p>${e.text}</p><div class="tag">${e.star}</div></div>`).join('')}</section><aside class="card gold"><h3>What Ladd_r can do with a log</h3><ul class="cleanlist"><li>Help tackle the situation now</li><li>Earmark it for an interview</li><li>Turn it into STAR structure</li><li>Suggest a résumé bullet</li><li>Save it for a performance review</li></ul></aside></div>`)}
function addExperience(){const t=$('#expTitle').value.trim(),x=$('#expText').value.trim();if(!t||!x){toast('Add a title and a short description.');return}state.experiences.unshift({title:t,text:x,star:'New story · needs result'});save();toast('Experience saved.');go('diary')}
function setPlan(p){state.plan=p;if(p==='core'&&state.credits<5)state.credits=5;if(p==='grow'&&state.credits<5)state.credits=5;save();toast(`Demo plan changed to ${p}.`);go('dashboard')}
function addCredits(n){state.credits+=n;save();toast(`Added ${n} demo résumé credit${n>1?'s':''}.`)}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function go(page){location.hash=page;render()}
function render(){
  try{
    const p=(location.hash||'#landing').slice(1);
    const view={landing,pricing,dashboard,matches,applications,resumes,interview,grow,diary}[p]||landing;
    app.innerHTML=view();
    window.scrollTo(0,0);
  }catch(err){
    app.innerHTML='<main class="landing"><section class="section"><div class="card coral"><h1>Ladd_r preview hit a loading error.</h1><p>Please refresh this page. If it persists, the preview will show this message instead of a blank screen while we fix it.</p><pre style="white-space:pre-wrap">'+String(err)+'</pre></div></section></main>';
  }
}
window.addEventListener('hashchange',render);
render();
